import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

function Home() {
  const router = useRouter();

  const gotoAuthPage = () => {
    router.push("/authenticated");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>GOODBYE WORLD</h1>
        <Link href="/dad-joke">
          <a>Dad Joke</a>
        </Link>

        <div>
          <button onClick={gotoAuthPage}>Auth Page</button>
        </div>
      </div>
    </div>
  );
}

export default Home;
